### ISSUE TITLE
Missing dependencies for SOCKS support

### ISSUE THREAD

**Issue by japa-fi** [taskinen/yle-dl-docker#10]
1) Make ssh-tunnel: ssh somehost -D 1080
2) execute yle-dl with proxy parameter: docker run --rm -ti -u=$(id -u):$(id -g) -v "$(pwd)":/out taskinen/yle-dl https://areena.yle.fi/1-50621997 --proxy socks5://localhost:1080

-> 
Requests.exceptions.InvalidSchema: Missing dependencies for SOCKS support.

The same parameter works on my locally compiled version of yle-dl but I have my reasons to run it in container on another host.

**Comment by taskinen** [comment]
Thanks @japa-fi for this finding! Added support for SOCKS proxies now.
