### ISSUE TITLE
Docker run returning: ERROR: No streams found 

### ISSUE THREAD

**Issue by attiolli** [taskinen/yle-dl-docker#13]
Hi,

Docker run fails with the **No streams found error**.

I ran the docker like this (debug activated):
attley@jarvis:~/docker/yle-dl$ docker run --rm -ti -u=$(id -u):$(id -g) -v "$(pwd)":/out taskinen/yle-dl https://areena.yle.fi/audio/1-1440981 --latestepisode -o uutiset.mp3 -VV
yle-dl 20210808: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2021 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3

DEBUG: https://areena.yle.fi/audio/1-1440981 is an audio URL
DEBUG: HTTP GET https://areena.yle.fi/audio/1-1440981
DEBUG: HTTP status code: 200
DEBUG: HTTP response headers:
DEBUG: Content-Type: text/html; charset=utf-8
DEBUG: Transfer-Encoding: chunked
DEBUG: Connection: keep-alive
DEBUG: Server: CloudFront
DEBUG: Date: Mon, 21 Feb 2022 08:25:13 GMT
DEBUG: X-Powered-By: Express
DEBUG: X-Frame-Options: DENY
DEBUG: ETag: W/"3f80a-VgVOEm1zGhG0+/FID8qD1pEkPfw"
DEBUG: Content-Encoding: gzip
DEBUG: Vary: Accept-Encoding
DEBUG: X-Cache: Miss from cloudfront
DEBUG: Via: 1.1 ffa40c4091d11859ad05cf9748508c58.cloudfront.net (CloudFront)
DEBUG: X-Amz-Cf-Pop: ARN1-C1
DEBUG: X-Amz-Cf-Id: QJ13Y8PqIyhYCbnaYk8NzK33KznDN7tCm6fhLGOlPbayLmzgKYQGjw==
DEBUG: HTML meta charset: UTF-8
DEBUG: Getting a playlist page 1-1440981, size = 100, offset = 0
DEBUG: HTTP GET https://areena.api.yle.fi/v1/ui/series/1-1440981/episodes?availability=ondemand&episodeDisplayOrder=latestFirst&language=fi&v=edge&client=yle-areena-web&app_id=areena_web_radio_prod&app_key=b3a0dc973c0aab997f1021bc7a0e3157&limit=100
DEBUG: HTTP status code: 200
DEBUG: HTTP response headers:
DEBUG: Content-Type: application/json
DEBUG: Content-Length: 3613
DEBUG: Connection: keep-alive
DEBUG: Date: Mon, 21 Feb 2022 08:25:13 GMT
DEBUG: Server: nginx/1.21.3
DEBUG: Expires: Mon, 21 Feb 2022 08:26:13 GMT
DEBUG: Warning: 299 areena-api "UI schema version 'edge' is Experimental"
DEBUG: Cache-Control: public, max-age=60
DEBUG: Content-Encoding: gzip
DEBUG: Vary: Origin,Accept-Encoding
DEBUG: X-Cache: RefreshHit from cloudfront
DEBUG: Via: 1.1 7f7d86a250c539fe4431535882cf4e4e.cloudfront.net (CloudFront)
DEBUG: X-Amz-Cf-Pop: ARN54-C1
DEBUG: X-Amz-Cf-Id: 8bW6JJ02IPAxh2pLZ9SQG2svxY2SUQV0nOxhYqUf_v-igqkwhCSZMg==
**ERROR: No streams found**

Running the latest image installed today 20220221:, image dated 6 months ago:
attley@jarvis:~/docker/yle-dl$ docker images
REPOSITORY                             TAG          IMAGE ID       CREATED         SIZE
taskinen/yle-dl                        latest       44178957b7a4   6 months ago    341MB

For refrence I have attached logs when I ran the native pip3 installed version (installed on debian 10 system today 20220221). Attached in file: "native-yle-dl-working-fine.txt".
[native-yle-dl-working-fine.txt](https://github.com/taskinen/yle-dl-docker/files/8107594/native-yle-dl-working-fine.txt)

Cheers,
Olli

**Comment by taskinen** [comment]
Thank you @attiolli for the very detailed bug report! I reproduced the error, and then fixed it by rebuilding my image with the latest yle-dl from pip. I guess yle-dl has fixed some bugs upstream. I should set an automatic build pipeline for my image, since this is not the first time.

Try to pull latest `taskinen/yle-dl` from Docker Hub and try again, thanks!

**Comment by attiolli** [comment]
I can confirm that the issue is now resolved. Thanks!

attley@jarvis:~/docker/yle-dl$ docker pull taskinen/yle-dl
Using default tag: latest
latest: Pulling from taskinen/yle-dl
59bf1c3509f3: Pull complete
2f39011a0243: Pull complete
80c9701287bd: Pull complete
fb1ee64726a6: Pull complete
Digest: sha256:4140bd6b901544f790077547d84a230b3ea84375f58a4acd8a71161ae5df94a1
Status: Downloaded newer image for taskinen/yle-dl:latest
docker.io/taskinen/yle-dl:latest

attley@jarvis:~/docker/yle-dl$ docker run --rm -ti -u=$(id -u):$(id -g) -v "$(pwd)":/out taskinen/yle-dl https://areena.yle.fi/audio/1-1440981 --latestepisode -o uutiset.mp3
yle-dl 20220213: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2022 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3
Output file: uutiset.mp3
size=    3260kB time=00:02:19.01 bitrate= 192.1kbits/s speed=1.3e+03x
Stream saved to uutiset.mp3
