### ISSUE TITLE
refresh docker image to newest yle-dl

### ISSUE THREAD

**Issue by svalavuo** [taskinen/yle-dl-docker#14]
There has happened a change in areena.yle.fi
Some kind of fix is available in master (https://github.com/aajanki/yle-dl/issues/304#issuecomment-1106760371)
Can this be updated to docker image as well?

- Samuli

**Comment by taskinen** [comment]
Hi @svalavuo! I just rebuilt the image and pushed that to Docker Hub.

I will make an automatic build pipeline for this.

**Comment by taskinen** [comment]
Alright, now I have a Github Action which builds and publishes the image. I didn't manage to trigger it automatically to @aajanki 's releases. I have to think what is the best way to automate this. But now it's at least as easy as triggering the pipeline manually.
