### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by Mateus109** [taskinen/yle-dl-docker#16]
Seems YLE may have removed (or changed) their streaming URL.  Possibly around 17th May.

**Comment by taskinen** [comment]
Hi @Mateus109! I just tested the latest Docker image with a recent episode from Areena, and it works for me. Although it gives couple of warnings about subtitles, the MKV-file it saves is fine and playable.

```
❯ docker run --rm -ti -u=$(id -u):$(id -g) -v "$(pwd)":/out taskinen/yle-dl https://areena.yle.fi/1-50953471
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
yle-dl 20220425: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2022 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3

Output file: Au pairit Panamassa: Tropiikki kutsuu, vamos!: E01-2022-05-25T20:00.mkv
[hls @ 0x4003beb640] Can't support the subtitle(uri: https://ylekaodamd.akamaized.net/s/fhls/p/1955031/sp/195503100/serveFlavor/entryId/1_a53b3ahi/v/1/ev/83/flavorId/1_dnflp0ku/name/a.srt/index.m3u8/index.m3u8?__hdnea__=st=1653635115~exp=1653721515~acl=/s/fhls/p/1955031/sp/195503100/serveFlavor/entryId/1_a53b3ahi/v/1/ev/83/flavorId/1_*~hmac=196120e9e4cd098080c10394611d0bf69856281cef04b1be833c68adae1fcafb)
[hls @ 0x4003beb640] Can't support the subtitle(uri: https://ylekaodamd.akamaized.net/s/fhls/p/1955031/sp/195503100/serveFlavor/entryId/1_a53b3ahi/v/1/ev/83/flavorId/1_iuvx415k/name/a.srt/index.m3u8/index.m3u8?__hdnea__=st=1653635115~exp=1653721515~acl=/s/fhls/p/1955031/sp/195503100/serveFlavor/entryId/1_a53b3ahi/v/1/ev/83/flavorId/1_*~hmac=196120e9e4cd098080c10394611d0bf69856281cef04b1be833c68adae1fcafb)
Unsupported codec with id 100358 for input stream 2
[webvtt @ 0x400703b340] Dropping 40 duplicated subtitle events
[webvtt @ 0x4007ebb040] Dropping 139 duplicated subtitle events
frame=42851 fps=1016 q=-1.0 Lsize=  841659kB time=00:28:34.07 bitrate=4022.5kbits/s speed=40.6x
Stream saved to Au pairit Panamassa: Tropiikki kutsuu, vamos!: E01-2022-05-25T20:00.mkv
```

Can you please describe in more detail, what is the error you are encountering, what version of yle-dl you are using (in my example above the version is 20220425). Make sure you are using my latest Docker image (docker pull taskinen/yle-dl) before trying. Because there were some changes in Yle infrastructure ("Uusittu Areena") in April (referenced in issue #14).

If you are still facing problems, please reopen this issue.

**Comment by taskinen** [comment]
Ok @Mateus109 there is definetely some incompatibilities between current Areena and yle-dl. I just encountered an error while downloading that exact same episode with the newest yle-dl (20220518) but it still works with 20220425.

I built the three latest yle-dl versions as Docker images and pushed them as separate tags, so try if any of them works for you.

https://hub.docker.com/repository/docker/taskinen/yle-dl/tags?page=1&ordering=name

**Comment by Mateus109** [comment]
Hei @taskinen, anteeksi!  My mistake, yle-dl does seem to be working now.  I notice, however, that their live streams are not up todate. e.g. https://yletv-lh.akamaihd.net/i/yletv1hls_1@103188/index_4096_av-p.m3u8 is showing programmes from 16th May.  Onpa outoa!
